/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import app.bible.ui.Settings;
import controllers.ChapterController;
import controllers.VerseController;
import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;
import models.BookModel;
import models.ChapterModel;
import models.Finder;
import models.Vmodel;

/**
 *
 * @author pretizy
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        oldmodel= new BookModel(1, "old");
        newmodel= new BookModel(1, "new");
        o_cmodel= new ChapterModel(oldmodel);
        n_cmodel= new ChapterModel(newmodel);
        oldL = new Chap(oldmodel);
        jScrollPane4 = new javax.swing.JScrollPane();
        newL = new Chap(newmodel);
        jScrollPane1 = new javax.swing.JScrollPane();
        chap1 = new Chap(o_cmodel);
        jScrollPane2 = new javax.swing.JScrollPane();
        vmodel= new Vmodel(o_cmodel);
        verseList = new JList(vmodel);
        c_control= new ChapterController(oldL, newL, o_cmodel);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        v_control= new VerseController(chap1, o_cmodel, vmodel, jLabel1);
        jLabel2 = new javax.swing.JLabel();
        setting= new Settings(this, false, jLabel2, verseList);
        setting.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JBIBLE");
        setBackground(new java.awt.Color(255, 51, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oldL.setBackground(new java.awt.Color(45, 12, 12));
        oldL.setForeground(new java.awt.Color(204, 255, 204));
        oldL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        oldL.setNextFocusableComponent(chap1);
        oldL.setSelectionBackground(new java.awt.Color(255, 255, 255));
        oldL.setSelectionForeground(new java.awt.Color(0, 0, 255));
        oldL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                oldLValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(oldL);

        jTabbedPane1.addTab("Old", jScrollPane3);

        newL.setBackground(new java.awt.Color(45, 12, 12));
        newL.setForeground(new java.awt.Color(0, 0, 255));
        newL.setSelectionBackground(new java.awt.Color(255, 255, 255));
        newL.setSelectionForeground(new java.awt.Color(0, 0, 255));
        newL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                newLValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(newL);

        jTabbedPane1.addTab("New", jScrollPane4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 36, 120, 281));

        chap1.setBackground(new java.awt.Color(45, 12, 12));
        chap1.setForeground(new java.awt.Color(102, 102, 255));
        chap1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        chap1.setSelectionForeground(new java.awt.Color(255, 51, 51));
        chap1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                chap1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(chap1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 36, 120, 281));

        verseList.setBackground(new java.awt.Color(255, 255, 255));
        verseList.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(verseList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 36, 319, 281));

        jButton1.setText("Settings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 6, -1, -1));

        jButton2.setText("Speaker");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 6, -1, -1));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 6, -1, -1));

        jLabel1.setText("Genesis, 1 vs 1-50");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 355, 310, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bible1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 660, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String txt = JOptionPane.showInputDialog(this, "Type in the Search Keyewords");
        //create new Finder object
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this, "No input entered");
        } else {
            Finder find = new Finder();
            List list = find.search(txt);
            //check if search was found, if found then show search results
            if (list.size() > 0) {
                vmodel.setVerse(list);
                jLabel1.setText("Search found:  " + list.size() + " results found for " + txt);
            } else {
                JOptionPane.showMessageDialog(this, "No search result found");
                jLabel1.setText("No results found");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void chap1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_chap1ValueChanged
        
    }//GEN-LAST:event_chap1ValueChanged

    private void newLValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_newLValueChanged

        //    o_cmodel.setChapter(newL.getSelectedIndex(), new BookModel(newL.getSelectedIndex(), "new"));
    }//GEN-LAST:event_newLValueChanged

    private void oldLValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_oldLValueChanged
        
    }//GEN-LAST:event_oldLValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setting.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.Chap chap1;
    private javax.swing.JButton jButton1;
    private Settings setting;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private view.Chap newL;
    private BookModel oldmodel;
    private BookModel newmodel;
    private ChapterModel o_cmodel;
    private ChapterModel n_cmodel;
    private view.Chap oldL;
    private Vmodel vmodel;
    private javax.swing.JList verseList;
    private ChapterController c_control;
    private VerseController v_control;
    // End of variables declaration//GEN-END:variables
}
